name: Build DB Grep Tool

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - run: chmod +x ./gradlew
      - run: ./gradlew build --no-daemon
      - name: Archive package artifacts
          uses: actions/upload-artifact@v3
          with:
            name: release
            path: build/lib/*-all.jar